export default {
  plantNum: 3,

  sliders: [
    {
      label: "Recursion Depth",
      key: "recursionDepth",
      min: 0,
      init: 7,
      max: 7,
      step: 1,
      precision: 0,
    },
    {
      label: "Size",
      key: "size",
      min: 0,
      init: 100,
      max: 200,
      step: 1,
      precision: 0,
    },
    {
      label: "Branck Min Length",
      key: "branchMinLength",
      min: 0.0,
      init: 1.0,
      max: 10.0,
      step: 0.1,
      precision: 1,
    },
    {
      label: "Decreasing Coefficient A",
      key: "decCoeffA",
      min: 0.00,
      init: 0.90,
      max: 1.00,
      step: 0.01,
      precision: 2,
    },
    {
      label: "Decreasing Coefficient B",
      key: "decCoeffB",
      min: 0.00,
      init: 0.90,
      max: 1.00,
      step: 0.01,
      precision: 2,
    },
    {
      label: "Thickness",
      key: "thickness",
      min: 0.00,
      init: 1.00,
      max: 2.00,
      step: 0.01,
      precision: 2,
    },
    {
      label: "Angle α",
      key: "alpha",
      min: 0.000,
      init: Math.PI / 8,
      max: Math.PI / 4,
      step: 0.001,
      precision: 3,
    },
    {
      label: "Angle Δα",
      key: "deltaAlpha",
      min: -Math.PI / 8,
      init: 0,
      max: Math.PI / 8,
      step: 0.001,
      precision: 3,
    },
    {
      label: "Angle Δβ",
      key: "deltaBeta",
      min: -Math.PI / 8,
      init: 0,
      max: Math.PI / 8,
      step: 0.001,
      precision: 3,
    },
    {
      label: "Angle γ",
      key: "gamma",
      min: -Math.PI / 4,
      init: 0,
      max: Math.PI / 4,
      step: 0.001,
      precision: 3,
    },
    {
      label: "Randomization",
      key: "randomization",
      min: 0.0,
      init: 2.0,
      max: 10.0,
      step: 0.01,
      precision: 2,
    },
    {
      label: "Hue",
      key: "hue",
      min: 0,
      init: 180,
      max: 360,
      step: 1,
      precision: 0,
    },
    {
      label: "Saturation",
      key: "saturation",
      min: 0,
      init: 100,
      max: 100,
      step: 1,
      precision: 0,
    },
    {
      label: "Brightness",
      key: "brightness",
      min: 0.00,
      init: 1.00,
      max: 1.00,
      step: 0.01,
      precision: 2,
    },
  ],
};
